name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on version tags

jobs:
  tag-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install Poetry Plugins
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Install Dependencies
        run: poetry install --only main

      - name: Build the Package
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build -vvv
